version: "3.7"
services:
  mcp-calendar-service:
    image: gg3t/mcp-calendar-service:0.1.0  # Utilize a imagem construída a partir do seu Dockerfile
    networks:
      - ChatgmNET
    environment:
      # Ambiente de produção
      - SERVER_PORT=3500
      - SPRING_PROFILES_ACTIVE=prod
      # Configurações do banco de dados (mantenha as mesmas do seu application.properties)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://178.156.146.193:5432/callback_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=71d14724653158e0e40fd03f522ac11c
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mcp-calendar.rule=Host(`mcp-calendar.chatgmia.org`)"
        - "traefik.http.routers.mcp-calendar.entrypoints=websecure"
        - "traefik.http.routers.mcp-calendar.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.mcp-calendar.loadbalancer.server.port=3500"
        # Configurações para WebSockets e SSE
        - "traefik.http.middlewares.sseheader.headers.customrequestheaders.Cache-Control=no-cache"
        - "traefik.http.middlewares.sseheader.headers.customresponseheaders.Cache-Control=no-cache"
        - "traefik.http.middlewares.sseheader.headers.customresponseheaders.Content-Type=text/event-stream"
        - "traefik.http.middlewares.sseheader.headers.customresponseheaders.Connection=keep-alive"
        - "traefik.http.middlewares.sseheader.headers.customresponseheaders.X-Accel-Buffering=no"
        - "traefik.http.routers.mcp-calendar.middlewares=sseheader@docker"
    restart: always
    # Não exponha a porta externamente, pois o Traefik fará o roteamento.
networks:
  ChatgmNET:
    external: true
    attachable: true
